# Site settings
title: Portfolioblomi
baseurl: "/slim"
email: haluskua.one@gmail.com
url: ""
tagline: "A basic exercise test to Jekyll"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 
