# Site settings
title: Portfolio-bilong-mi
baseurl: "/slim"
email: haluskua.one@gmail.com
url: ""
tagline: "run by jekyll on github"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 


